### ISSUE TITLE
Implementation Details of Masked Images

### ISSUE THREAD

**Issue by Haochen-Wang409** [lhoyer/MIC#1]
Great work by leveraging masked image modeling (MIM) to learn target context!

I am asking for implementation details of masked images. 
Specifically, how to make the encoder deal with masked images? Did you introduce extra ```mask tokens```? Or, did you simply follow MAE, taking only visible patches as input (but this can not be achieved with CNN-based models)?

Looking forward to your reply.

**Comment by lhoyer** [comment]
Thank you for your interest in our work! 

The masking is applied to the input image. Random patches of the image are replaced with zero values, which corresponds to the mean color (some gray tone) due to normalization. These modified images are used as masked input for the network. Therefore, it can be applied both to Transformers and CNNs. The advantage of this masking strategy is that it is easy to implement and works regardless of the network architecture. You can find the implementation of the masking here:

https://github.com/lhoyer/MIC/blob/master/seg/mmseg/models/utils/masking_transforms.py

**Comment by Haochen-Wang409** [comment]
Thanks for your prompt reply :)
